apiVersion: v1
kind: Service
metadata:
  name: stress-service
spec:
  selector:
    app: stress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  labels:
    app: stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: yourusername/stress-app:v1
        ports:
        - containerPort: 8000
        # НЕТ ЛИМИТОВ - съест все ресурсы!
